

spring:
  application:
    name: provider-ticket   # provider应用名称


server:
  port: 8001    # provider端口


eureka:
  instance:
    prefer-ip-address: true   # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    # eureka的服务地址